---

- name: install some stuff
  hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
  - name: install epel-release
    yum: name=epel-release state=present
  - name: install python-pip
    yum: name=python-pip state=present
  - name: install vim
    yum: name=vim state=present
  - name: disable selinux
    selinux: state=disabled
  - name: import mongo rpm pub key
    shell: sudo rpm --import https://www.mongodb.org/static/pgp/server-3.2.asc
  - name: configure mongo yum repo
    copy: src=files/mongo.repo dest=/etc/yum.repos.d/
  - name: install mongodb server
    yum: name=mongodb-org state=present
  - name: enable start mongod
    service: name=mongod enabled=yes state=restarted
  - name: pip install flask
    pip: name=flask
  - name: pip install pymongo
    pip: name=pymongo
  - name: copy flask app
    copy: src=files/dr-app.py dest=/home/vagrant mode=0755
  - name: copy flask systemd file
    copy: src=files/flask.service dest=/etc/systemd/system
  - name: enable start flask app
    service: name=flask enabled=yes state=started
